/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jddevaughnbrown' at '10/31/17 8:08 AM' with Gradle 2.14.1
 *
 * @author jddevaughnbrown, @date 10/31/17 8:08 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
