import org.junit.Test;
import static org.junit.Assert.*;

import edu.princeton.cs.algs4.Counter;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jddevaughnbrown' at '10/31/17 8:08 AM' with Gradle 2.14.1
 *
 * @author jddevaughnbrown, @date 10/31/17 8:08 AM
 */
public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test
    public void testCounter() {
      Counter count = new Counter("0");
      count.increment();
      assertEquals("Should be 1", 1, count.tally());
      
    }
    
    
}
